In [1]:
import numpy as np
x=np.array([[1,2,3],[4,5,6,]])
print(x)

[[1 2 3]
 [4 5 6]]


In [2]:
from scipy import sparse
y=np.eye(4)
print(y)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [12]:
from sklearn.datasets import load_iris
iris_dataset=load_iris()
print(iris_dataset.keys())

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename'])


In [34]:
import pandas as pd
import numpy as np
data=pd.read_csv('data.csv')
print(data)
print()
input=np.array(data)[:,:-1]
print(input)
print()
output=np.array(data)[:,-1]
print(output)
print()
for element in enumerate(output):
    print (element)
print()

     sky air temp humidity    wind water forecast enjoy sport
0  sunny     warm   normal  strong  warm     same         yes
1  sunny     warm     high  strong  warm     same         yes
2  rainy     cold     high  strong  warm   change          no
3  sunny     warm     high  strong  cool   change         yes

[['sunny' 'warm' 'normal' 'strong' 'warm' 'same']
 ['sunny' 'warm' 'high' 'strong' 'warm' 'same']
 ['rainy' 'cold' 'high' 'strong' 'warm' 'change']
 ['sunny' 'warm' 'high' 'strong' 'cool' 'change']]

['yes' 'yes' 'no' 'yes']

(0, 'yes')
(1, 'yes')
(2, 'no')
(3, 'yes')



In [22]:
import pandas as pd
import numpy as np
data=pd.read_csv('data.csv')
x=data.iloc[:,:-1].values
y=data.iloc[:,-1].values
print(x)
print(y)

[['sunny' 'warm' 'high' 'strong' 'warm' 'same' 'yes']
 ['rainy' 'cold' 'high' 'strong' 'warm' 'change' 'no']
 ['sunny' 'warm' 'high' 'strong' 'cool' 'change' 'yes']]
['yes' 'yes' 'no' 'yes']
